### ISSUE TITLE
Video Only results on AudioSet-20K

### ISSUE THREAD

**Issue by GenjiB** [YuanGongND/cav-mae#2]
Hi,

I can reproduce the results of finetuning on Audioset 20K with the multimodal setting.
However, I tried to get the visual-only baseline from the multimodal pre-trained weights. I can only get 13.11 (missingvideoonly setting) and 12.7 (videoonly).

Pretrained ViT-B-16 on ImageNet-21K with multimodal script can get ~9.5mAP.
Pretrained CAV-MAE with audioonly script can get ~17.6 mAP.

Do you have the script for training videoonly baseline?

Thank you

**Comment by YuanGongND** [comment]
Hi Yan-Bo,

The reason that I prefer Github issue is I can easier quote the code & it can help people having same question with you. Hope it is understandable.

> I can reproduce the results of finetuning on Audioset 20K with the multimodal setting.

I actually doubt this point because the issue in the visual branch might be overshadowed as AudioSet mostly relies on audio. FYI, if you use our `scale++` pretrained model and have a similar training / evaluation set with us, the performance should be around 42.2 mAP ([training log](https://github.com/YuanGongND/cav-mae/blob/master/egs/audioset/training_logs/as20k_ft_42.2.txt)). 

> However, I tried to get the visual-only baseline from the multimodal pre-trained weights. I can only get 13.11 (missingvideoonly setting) and 12.7 (videoonly).

A few things: First, for video only model, you should set `skip_frame_agg` to False (i.e., using frame aggregation). I added a sample script [here](https://github.com/YuanGongND/cav-mae/blob/master/egs/audioset/run_cavmae_ft_bal_videoonly.sh), this will directly add a few points up (for us, about 3 mAP). Second, `missingvideoonly` means finetune a model with multi-modal data, but inference with only one, you should not use this mode for finetuning with single modality data.

> Pretrained ViT-B-16 on ImageNet-21K with multimodal script can get ~9.5mAP.

This seems to be low, especially consider it is a finetuned checkpoint. 

> Pretrained CAV-MAE with audioonly script can get ~17.6 mAP.

We got 38.2 mAP. Please see [training log](https://github.com/YuanGongND/cav-mae/blob/master/egs/audioset/training_logs/as20k_ft_audioonly_38.2.txt). I am wondering what's the mAP of your MM ft on AS-20k.

Finally, I added AS-20K audio- and visual- only [pretrained checkpoints](https://github.com/YuanGongND/cav-mae/tree/master/pretrained_model), [training scripts](https://github.com/YuanGongND/cav-mae/tree/master/egs/audioset), [training logs](https://github.com/YuanGongND/cav-mae/tree/master/egs/audioset/training_logs). Please make sure you use our code without any change. I feel there's a error in either training or data based on the numbers you reported, especially "Pretrained CAV-MAE with audioonly script can get ~17.6 mAP.", that is over 20 mAP difference.

-Yuan

**Comment by GenjiB** [comment]
Sorry for the confusion. 

> Pretrained CAV-MAE with audioonly script can get ~17.6 mAP.
I trained videoonly baseline with audioonly script by changing mode.

Thanks for the reply. After setting `skip_frame_agg`  to False. I can reach 19.8 mAp.

**Comment by YuanGongND** [comment]
Thanks for the clarification. Yes, 19.8 is very close (and is the exact number in the paper).
